### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by Panshangka** [Ascend/sample-facialrecognition#3]
我的ubuntu版本是16.04.3，内核原版本为4.10，升级之后为4.18.3（手动下载内核升级，官网文档给的patch.diff文件打不了补丁），然后在配置交叉编译环境时出现gcc-aarch64-linux-gnu与g++aarch64-linux-gnu安装不了的原因，究其原因为一些底层依赖有问题，于是手动下载deb包安装，之后交叉环境没有问题了,SD 卡也显示制作成功。但是按照https://github.com/Ascend/samplefacialrecognition/blob/master/README_cn.md这个的地址的sample执行部署bash deploy.sh 192.168.1.2 internet时，出现以下错误：
`/home/psk/tools/che/ddk/ddk/include/libc_sec/include/securec.h:472:46: error: expected primary-expression before ‘const’
     SECUREC_API int vfwscanf_s(FILE *stream, const wchar_t *format, va_list argList);
                                              ^~~~~
/home/psk/tools/che/ddk/ddk/include/libc_sec/include/securec.h:472:77: error: expected primary-expression before ‘argList’
 CUREC_API int vfwscanf_s(FILE *stream, const wchar_t *format, va_list argList);
                                                                       ^~~~~~~

/home/psk/tools/che/ddk/ddk/include/libc_sec/include/securec.h:472:84: error: expression list treated as compound expression in initializer [-fpermissive]
 CUREC_API int vfwscanf_s(FILE *stream, const wchar_t *format, va_list argList);
                                                                              ^

make: *** [out/obj/src/ascenddk/ascend_ezdvpp/dvpp_utils.o] Error 1
ERROR: compile ezdvpp failed, please check the env.
`

**Comment by ascendhuawei** [comment]
你好，studio是否已经安装，更新代码之后，看看还有没有类似问题？

**Comment by Panshangka** [comment]
重装系统，不升级内核就没问题了，还是4.10的内核

**Comment by ascendhuawei** [comment]
OK，我们后面也会优化这块的内容，同时也欢迎使用我们的新版本~

**Comment by ascendhuawei** [comment]
不升级内核应该也没有问题，暂时先用，如果遇到问题再解决吧。

 

发件人: Panshangka [mailto:notifications@github.com] 
发送时间: 2019年7月2日 14:37
收件人: Ascend/sample-facialrecognition <sample-facialrecognition@noreply.github.com>
抄送: ascendhuawei <ascend@huawei.com>; Comment <comment@noreply.github.com>
主题: Re: [Ascend/sample-facialrecognition] 部署出错 (#3)

 

重装系统，不升级内核就没问题了，还是4.10的内核
